# Requirements automatically generated by pigar.
# https://github.com/damnever/pigar

# PAN-Card-OCR-master/src/crop_to_box.py: 9
# ocr.py: 3
# ocr_surveyor.py: 4
Pillow == 5.3.0

# parivahan-py-master/parivahan/__init__.py: 12
beautifulsoup4 == 4.6.3

# parivahan-py-master/parivahan/__init__.py: 13
get_captcha == 0.2.0

# solving_captchas_code_examples/solving_captchas_code_examples/extract_single_letters_from_captchas.py: 5
# solving_captchas_code_examples/solving_captchas_code_examples/helpers.py: 1
# solving_captchas_code_examples/solving_captchas_code_examples/solve_captchas_with_model.py: 3,5
# solving_captchas_code_examples/solving_captchas_code_examples/train_model.py: 5
imutils == 0.5.2

# parivahan-py-master/parivahan/__init__.py: 14
mechanize == 0.4.2

# ocr.py: 6
# ocr_surveyor.py: 7
# solving_captchas_code_examples/solving_captchas_code_examples/solve_captchas_with_model.py: 4
# solving_captchas_code_examples/solving_captchas_code_examples/train_model.py: 4
numpy == 1.15.4

# ocr.py: 5
# ocr_surveyor.py: 6
# solving_captchas_code_examples/solving_captchas_code_examples/extract_single_letters_from_captchas.py: 3
# solving_captchas_code_examples/solving_captchas_code_examples/helpers.py: 2
# solving_captchas_code_examples/solving_captchas_code_examples/solve_captchas_with_model.py: 6
# solving_captchas_code_examples/solving_captchas_code_examples/train_model.py: 1
opencv_python == 4.1.0.25

# archive/dl.py: 34
pandas == 0.23.4

# ocr.py: 4
# ocr_surveyor.py: 5
pytesseract == 0.2.7

# parivahan-py-master/parivahan/__init__.py: 15
requests == 2.21.0

# solving_captchas_code_examples/solving_captchas_code_examples/train_model.py: 6,7
scikit_learn == 0.20.1

# archive/src/parivahan/setup.py: 4
# parivahan-py-master/setup.py: 4
setuptools == 40.6.3
